package cmpp30

import (
	sms "github.com/hujm2023/go-sms-protocol"
	"github.com/hujm2023/go-sms-protocol/cmpp"
	"github.com/hujm2023/go-sms-protocol/packet"
)

// Submit represents a CMPP 3.0 Submit PDU.
// It is used by the SP to submit a short message to the ISMG.
type Submit struct {
	cmpp.Header
	// MsgID is the message identifier (8 bytes), generated by the SP gateway, left blank here.
	MsgID uint64

	// PkTotal is the total number of packets for the same MsgID (1 byte, starts from 1).
	PkTotal uint8

	// PkNumber is the sequence number for the same MsgID (1 byte, starts from 1).
	PkNumber uint8

	// RegisteredDelivery indicates if a status report is required (1 byte):
	// 0=No, 1=Yes, 2=Generate SMC bill (for billing only, not sent to terminal).
	RegisteredDelivery uint8

	// MsgLevel is the message priority level (1 byte).
	MsgLevel uint8

	// ServiceID is the service type (10 bytes), a combination of digits, letters, and symbols.
	ServiceID string

	// FeeUserType indicates the billing user type (1 byte):
	// 0=Destination terminal, 1=Source terminal, 2=SP, 3=Field invalid (refer to FeeTerminalID).
	FeeUserType uint8

	// FeeTerminalID is the billed user's number (32 bytes).
	// If blank, field is invalid (refer to FeeUserType, mutually exclusive).
	FeeTerminalID string

	// FeeTerminalType is the billed user's number type (1 byte): 0=Real number, 1=Pseudo code.
	FeeTerminalType uint8

	// TpPID is the GSM protocol type (1 byte). See GSM 03.40 section 9.2.3.9.
	TpPID uint8

	// TpUDHI is the GSM protocol type (1 byte).
	// See GSM 03.40 section 9.2.3.23 (only 1 bit used, right-aligned).
	TpUDHI uint8

	// MsgFmt is the message format (1 byte):
	// 0=ASCII, 3=SMS Write Card, 4=Binary, 8=UCS2, 15=GB Hanzi.
	MsgFmt uint8

	// MsgSrc is the message source (SP ID) (6 bytes).
	MsgSrc string

	// FeeType is the fee category (2 bytes):
	// 01: Free for 'FeeTerminalID'
	// 02: Per-message fee for 'FeeTerminalID'
	// 03: Monthly fee for 'FeeTerminalID'
	// 04: Capped fee for 'FeeTerminalID'
	// 05: Fee handled by SP for 'FeeTerminalID'
	FeeType string

	// FeeCode is the fee code (6 bytes, in cents).
	FeeCode string

	// ValiDTime is the validity period (17 bytes, SMPP 3.3 format).
	ValiDTime string

	// AtTime is the scheduled delivery time (17 bytes, SMPP 3.3 format).
	AtTime string

	// SrcID is the source number (21 bytes).
	// SP's service code or long number prefixed with it. Displayed as sender on user's phone.
	// Corresponds to userExt field in our implementation.
	SrcID string

	// DestUsrTL is the number of recipient users (1 byte, < 100).
	DestUsrTL uint8

	// DestTerminalID is the list of recipient MSISDNs (32 * DestUsrTL bytes).
	// Each MSISDN is 32 bytes.
	DestTerminalID []string

	// DestTerminalType is the recipient users' number type (1 byte): 0=Real number, 1=Pseudo code.
	DestTerminalType uint8

	// MsgLength is the message length (1 byte).
	// MsgFmt=0: <160 bytes; Others: <=140 bytes.
	MsgLength uint8

	// MsgContent is the message content (MsgLength bytes).
	MsgContent string

	// LinkID is used for on-demand services (20 bytes).
	// Not used in non-on-demand MT processes.
	LinkID string
}

// IDecode decodes the byte slice into a Submit PDU.
func (s *Submit) IDecode(data []byte) error {
	if len(data) < 4 {
		return cmpp.ErrInvalidPudLength
	}
	b := packet.NewPacketReader(data)
	defer b.Release()

	s.Header = cmpp.ReadHeader(b)
	s.MsgID = b.ReadUint64()
	s.PkTotal = b.ReadUint8()
	s.PkNumber = b.ReadUint8()
	s.RegisteredDelivery = b.ReadUint8()
	s.MsgLevel = b.ReadUint8()
	s.ServiceID = b.ReadCStringN(10)
	s.FeeUserType = b.ReadUint8()
	s.FeeTerminalID = b.ReadCStringN(32)
	s.FeeTerminalType = b.ReadUint8()
	s.TpPID = b.ReadUint8()
	s.TpUDHI = b.ReadUint8()
	s.MsgFmt = b.ReadUint8()
	s.MsgSrc = b.ReadCStringN(6)
	s.FeeType = b.ReadCStringN(2)
	s.FeeCode = b.ReadCStringN(6)
	s.ValiDTime = b.ReadCStringN(17)
	s.AtTime = b.ReadCStringN(17)
	s.SrcID = b.ReadCStringN(21)
	s.DestUsrTL = b.ReadUint8()
	s.DestTerminalID = make([]string, s.DestUsrTL)
	for i := 0; i < int(s.DestUsrTL); i++ {
		s.DestTerminalID[i] = b.ReadCStringN(32)
	}
	s.DestTerminalType = b.ReadUint8()
	s.MsgLength = b.ReadUint8()
	s.MsgContent = string(b.ReadNBytes(int(s.MsgLength)))
	s.LinkID = b.ReadCStringN(20)

	return b.Error()
}

// IEncode encodes the Submit PDU into a byte slice.
func (s *Submit) IEncode() ([]byte, error) {
	b := packet.NewPacketWriter()

	cmpp.WriteHeaderNoLength(s.Header, b)
	b.WriteUint64(s.MsgID)
	b.WriteUint8(s.PkTotal)
	b.WriteUint8(s.PkNumber)
	b.WriteUint8(s.RegisteredDelivery)
	b.WriteUint8(s.MsgLevel)
	b.WriteFixedLenString(s.ServiceID, 10)
	b.WriteUint8(s.FeeUserType)
	b.WriteFixedLenString(s.FeeTerminalID, 32)
	b.WriteUint8(s.FeeTerminalType)
	b.WriteUint8(s.TpPID)
	b.WriteUint8(s.TpUDHI)
	b.WriteUint8(s.MsgFmt)
	b.WriteFixedLenString(s.MsgSrc, 6)
	b.WriteFixedLenString(s.FeeType, 2)
	b.WriteFixedLenString(s.FeeCode, 6)
	b.WriteFixedLenString(s.ValiDTime, 17)
	b.WriteFixedLenString(s.AtTime, 17)
	b.WriteFixedLenString(s.SrcID, 21)
	b.WriteUint8(s.DestUsrTL)
	for _, id := range s.DestTerminalID {
		b.WriteFixedLenString(id, 32)
	}
	b.WriteUint8(s.DestTerminalType)
	b.WriteUint8(s.MsgLength)
	b.WriteFixedLenString(s.MsgContent, int(s.MsgLength))
	b.WriteFixedLenString(s.LinkID, 20)

	return b.BytesWithLength()
}

// SetSequenceID sets the sequence ID of the PDU.
func (s *Submit) SetSequenceID(id uint32) {
	s.Header.SequenceID = id
}

// GetSequenceID returns the sequence ID of the PDU.
func (s *Submit) GetSequenceID() uint32 {
	return s.Header.SequenceID
}

// GetCommand returns the command ID of the PDU.
func (s *Submit) GetCommand() sms.ICommander {
	return cmpp.CommandSubmit
}

// GenEmptyResponse generates an empty response PDU for the Submit.
func (s *Submit) GenEmptyResponse() sms.PDU {
	return &SubmitResp{
		Header: cmpp.Header{
			CommandID:  cmpp.CommandSubmitResp,
			SequenceID: s.GetSequenceID(),
		},
	}
}

// String returns a string representation of the Submit PDU.
func (s *Submit) String() string {
	w := packet.NewPDUStringer()
	defer w.Release()

	w.Write("Header", s.Header)
	w.Write("MsgID", s.MsgID)
	w.Write("PkTotal", s.PkTotal)
	w.Write("PkNumber", s.PkNumber)
	w.Write("RegisteredDelivery", s.RegisteredDelivery)
	w.Write("MsgLevel", s.MsgLevel)
	w.Write("ServiceID", s.ServiceID)
	w.Write("FeeUserType", s.FeeUserType)
	w.Write("FeeTerminalID", s.FeeTerminalID)
	w.Write("FeeTerminalType", s.FeeTerminalType)
	w.Write("TpPID", s.TpPID)
	w.Write("TpUDHI", s.TpUDHI)
	w.Write("MsgFmt", s.MsgFmt)
	w.Write("MsgSrc", s.MsgSrc)
	w.Write("FeeType", s.FeeType)
	w.Write("FeeCode", s.FeeCode)
	w.Write("ValiDTime", s.ValiDTime)
	w.Write("AtTime", s.AtTime)
	w.Write("SrcID", s.SrcID)
	w.Write("DestUsrTL", s.DestUsrTL)
	w.Write("DestTerminalID", s.DestTerminalID)
	w.Write("DestTerminalType", s.DestTerminalType)
	w.Write("MsgLength", s.MsgLength)
	w.WriteWithBytes("MsgContent", s.MsgContent)
	w.Write("LinkID", s.LinkID)

	return w.String()
}

// SubmitResp represents a CMPP 3.0 SubmitResp PDU.
// It is the response to a Submit PDU.
type SubmitResp struct {
	cmpp.Header
	// MsgID is the message identifier (8 bytes), generated by the ISMG.
	MsgID uint64

	// Result indicates the submission result (4 bytes):
	// 0: Success
	// 1: Invalid message structure
	// 2: Invalid command word
	// 3: Invalid message sequence number
	// 4: Invalid message length
	// 5: Invalid fee code
	// 6: Message length exceeds maximum
	// 7: Invalid ServiceID
	// 8: Flow control error
	// 9: Message requires resubmission
	// 10: Invalid MsgSrc
	// 11: Invalid FeeType
	// 12: Invalid FeeCode
	// 13: Invalid ValiDTime
	// 14: Invalid AtTime
	// 15: Invalid SrcID
	// 16: Invalid DestUsrTL
	// 17: Invalid DestTerminalID
	// 18: Invalid MsgLength
	// 19: Invalid MsgContent
	// 20: Invalid FeeTerminalID
	// >20: Other errors
	Result uint32
}

// IDecode decodes the byte slice into a SubmitResp PDU.
func (s *SubmitResp) IDecode(data []byte) error {
	if len(data) < cmpp.MinCMPPPduLength {
		return cmpp.ErrInvalidPudLength
	}

	b := packet.NewPacketReader(data)
	defer b.Release()

	s.Header = cmpp.ReadHeader(b)
	s.MsgID = b.ReadUint64()
	s.Result = b.ReadUint32()

	return b.Error()
}

// IEncode encodes the SubmitResp PDU into a byte slice.
func (s *SubmitResp) IEncode() ([]byte, error) {
	b := packet.NewPacketWriter()
	defer b.Release()

	cmpp.WriteHeaderNoLength(s.Header, b)
	b.WriteUint64(s.MsgID)
	b.WriteUint32(s.Result)

	return b.BytesWithLength()
}

// SetSequenceID sets the sequence ID of the PDU.
func (s *SubmitResp) SetSequenceID(id uint32) {
	s.Header.SequenceID = id
}

// GetSequenceID returns the sequence ID of the PDU.
func (s *SubmitResp) GetSequenceID() uint32 {
	return s.Header.SequenceID
}

// GetCommand returns the command ID of the PDU.
func (s *SubmitResp) GetCommand() sms.ICommander {
	return cmpp.CommandSubmitResp
}

// GenEmptyResponse generates an empty response PDU (nil for SubmitResp).
func (s *SubmitResp) GenEmptyResponse() sms.PDU {
	return nil
}

// String returns a string representation of the SubmitResp PDU.
func (s *SubmitResp) String() string {
	w := packet.NewPDUStringer()
	defer w.Release()

	w.Write("Header", s.Header)
	w.Write("MsgID", s.MsgID)
	w.Write("Result", s.Result)

	return w.String()
}
